---
language: python
python:   "2.7"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
    
before_install:
  - add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update -qq

install:
  - pip install ansible==2.2.0.0
  - sudo apt-get install -y -qq openjdk-8-jre
  - sudo apt-get remove -y --purge elasticsearch

script:
  - ansible-playbook tests/test_defaults.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local --sudo

  - ansible-playbook tests/test_plugins.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_plugins.yml -i localhost, --connection=local --sudo

# vi:ts=2:sw=2:et:ft=yaml
