---
language: python
python:   "2.7"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
    
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update -qq

install:
  - pip install ansible==2.3.0.0
  - sudo apt-get remove -y --purge elasticsearch
  - sudo apt-get install -y -qq openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

script:
  - java -version
  - ansible-playbook tests/test_defaults.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local --sudo

  - ansible-playbook tests/test_plugins.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_plugins.yml -i localhost, --connection=local --sudo

# vi:ts=2:sw=2:et:ft=yaml
