---

- name: ElasticSearch Yum Repository
  copy:
    dest: "/etc/yum.repos.d/elasticsearch-{{es_version}}.repo"
    content: "{{es_yum_config}}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: es_use_repo

- block:

  - name: Download ElasticSearch RPM
    get_url:
      url: "{{es_package_url}}"
      dest: "/var/cache/yum/{{ansible_architecture}}/elasticsearch-{{es_version}}.rpm"

  - name: Install ElasticSearch from RPM
    yum:
      name: "/var/cache/yum/{{ansible_architecture}}/elasticsearch-{{es_version}}.rpm"
      state: present
    notify: es restart

  when: not es_use_repo

# vi:ts=2:sw=2:et:ft=yaml
