---

- name: Data Directories
  file:
    state: directory
    dest: "{{item}}"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: "0750"
  with_items: "{{es_cfg_path_data}}"

- name: ElasticSearch JVM options
  copy:
    dest:    "{{es_config_dir}}/jvm.options"
    content: "{{es_config_jvm}}"
    owner:   "root"
    group:   "root"
    mode:    "0644"
  notify: elasticsearch restart

- name: Log4j2 properties
  template:
    src:   etc/elasticsearch/log4j2.properties.j2
    dest:  "{{es_config_dir}}/log4j2.properties"
    owner: "root"
    group: "root"
    mode:  "0644"
  notify: elasticsearch restart
  tags:
    - es_config
    - es_log4j2_properties

- name: elasticsearch.yml
  copy:
    dest:    /etc/elasticsearch/elasticsearch.yml
    owner:   "root"
    group:   "root"
    mode:    "0644"
    content: |
      # << Ansible managed file >>
      
      {{es_config|to_nice_yaml(indent=2)}}
      
  notify: elasticsearch restart

# vi:ts=2:sw=2:et:ft=yaml
