---
#
# Install package and dependencies
#

- name: Install prerequisites
  apt:
    name={{item}}
    state=present
  with_items: es.apt.pkg_prereqs

- name: Install package
  apt:
    name={{es.apt.pkg}}
    state=present

- name: Data Directory
  file:
    state=directory
    dest="{{item}}"
    owner="{{es.owner}}"
    group="{{es.group}}"
    mode='0750'
  with_items: es.config.path_data

# vi:ts=2:sw=2:et:ft=yaml
