---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  sudo: true
  tags: es_install

- include: config.yml
  sudo: yes
  tags: es_config


# vi:ts=2:sw=2:et:ft=yaml
