---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  become: true
  tags: es_install

- include: plugins.yml
  become: true
  tags: es_plugins

- include: config.yml
  become: true
  tags: es_config


# vi:ts=2:sw=2:et:ft=yaml
