---

- name: elasticsearch start
  service:
    name: elasticsearch
    state: started
  become: true

- name: elasticsearch stop
  service:
    name: elasticsearch
    state: stopped
  become: true

- name: elasticsearch restart
  service:
    name: elasticsearch
    state: restarted
  become: true
